apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-client
  labels:
    component: elasticsearch
    role: client
spec:
  replicas: 2
  template:
    metadata:
      labels:
        component: elasticsearch
        role: client        
    spec:
      serviceAccountName: elasticsearch
      containers:
      - name: es-client          
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: docker-registry.default.svc:5000/nuxeo/elasticsearch-image
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CLUSTER_NAME"
          value: cluster
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: "-Xms256m -Xmx256m"
        - name: DISCOVERY_SERVICE
          value: elasticsearch-discovery
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
        - name: config
          mountPath: /usr/share/elasticsearch/config
      initContainers:
      - command:
          - sysctl
          - '-w'
          - vm.max_map_count=262144
        image: busybox
        imagePullPolicy: IfNotPresent
        name: sysctl
        securityContext:
          privileged: true
      volumes:
          - emptyDir:
              medium: ""
            name: "storage"
          - name: config
            configMap:
              name: elasticsearch-config
